RestoMVC.Mvc/Models/ErrorViewModel.cs
namespace RestoMVC.Mvc.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

RestoMVC.Mvc/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RestoMVC.Mvc.Models;

namespace RestoMVC.Mvc.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

RestoMVC.Mvc/Controllers/PlatoController.cs
using Microsoft.AspNetCore.Mvc;
using RestoMVC.Core;

namespace RestoMVC.Mvc.Controllers
{

    public class PlatoController : Controller
    {
        private readonly IAdo Ado;
        public PlatoController(IAdo ado) => Ado = ado;
        public async Task<IActionResult> Index()
        {
            var platos = await Ado.ObtenerPlatoAsync();
            return View("Listado", platos);
        }



        [HttpGet]
        public IActionResult AltaPlato()
        {
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> AltaPlato(Plato plato)
        {
            await Ado.AltaPlatoAsync(plato);
            return RedirectToAction(nameof(Index));
        }



        [HttpPost]
        public async Task<IActionResult> EliminarPlato(Plato plato)
        {
            plato = await Ado.PlatoPorIdAsync(plato.Id);
            if (plato is null)
            {
                return NotFound();
            }
            else
                await Ado.EliminarPlatoAsync(plato);
            return RedirectToAction(nameof(Index));
        }



        [HttpGet]
        public async Task<IActionResult> ActualizarPlato(int id)
        {
            Plato platos = await Ado.PlatoPorIdAsync(id);
            if (platos is null)
            {
                return NotFound();
            }
            else
                return View(platos);
        }



        [HttpPost]
        public async Task<IActionResult> ActualizarPlatoAsync(Plato plato)
        {
            await Ado.ActualizarPlatoAsync(plato);
            await Ado.ActualizarPlatoAsync(plato);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Detalle(int id)
        {
            Plato plato = await Ado.PlatoPorIdAsync(id);
            if (plato is null)
            {
                return NotFound();
            }
            return View(plato);
        }

    }
}

RestoMVC.Mvc/Controllers/RestauranteController.cs
using Microsoft.AspNetCore.Mvc;
using RestoMVC.Core;

namespace RestoMVC.Mvc.Controllers
{

    public class RestauranteController : Controller
    {
        private readonly IAdo Ado;
        public RestauranteController(IAdo ado) => Ado = ado;
        public async Task<IActionResult> Index()
        {
            var restaurantes = await Ado.ObtenerRestauranteAsync();
            return View("Listado", restaurantes);
        }



        [HttpGet]
        public IActionResult AltaRestaurante()
        {
            return View();
        }



        [HttpPost]
        public async Task<IActionResult> AltaRestaurante(Restaurante restaurante)
        {
            await Ado.AltaRestauranteAsync(restaurante);
            return RedirectToAction(nameof(Index));
        }



        [HttpPost]
        public async Task<IActionResult> EliminarRestaurante(Restaurante restaurante)
        {
            restaurante = await Ado.RestaurantePorIdAsync(restaurante.Id);
            if (restaurante is null)
            {
                return NotFound();
            }
            else
                await Ado.EliminarRestauranteAsync(restaurante);
            return RedirectToAction(nameof(Index));
        }



        [HttpGet]
        public async Task<IActionResult> ActualizarRestaurante(int id)
        {
            Restaurante restos = await Ado.RestaurantePorIdAsync(id);
            if (restos is null)
            {
                return NotFound();
            }
            else
                return View(restos);
        }



        [HttpPost]
        public async Task<IActionResult> ActualizarRestauranteAsync(Restaurante restaurante)
        {
            await Ado.ActualizarRestauranteAsync(restaurante);
            await Ado.ActualizarRestauranteAsync(restaurante);
            return RedirectToAction(nameof(Index));
        }
        [HttpPost]
        public async Task<ActionResult> Login(Restaurante resto)
        {
            var log = await Ado.restoPorPassAsync(resto.Contrasenia, resto.Mail);
            if (log is null)
                return NotFound();
            return View(log);
        }
        [HttpGet]
        public async Task<IActionResult> Detalle(int id)
        {
            Restaurante restaurante = await Ado.RestaurantePorIdAsync(id);
            if (restaurante is null)
            {
                return NotFound();
            }
            return View(restaurante);
        }

    }
}

RestoMVC.Mvc/Views/Home/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <title>RestoMVC</title>
</head>

<body>
    <h2>Elegi donde entrar</h2>
    <a asp-controller="Restaurante" asp-action="Index">Restaurantes</a><br/>
    <a asp-controller="Plato" asp-action="Index">Plato</a><br>
    <a asp-controller="Categoria" asp-action="Index">Categorias</a>
</body>

</html>

RestoMVC.Mvc/Views/Plato/ActualizarPlato.cshtml
@model RestoMVC.Core.Plato
@{
    Layout = null;
}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <title>Actualizar - Plato</title>
</head>

<body>
    <form asp-action="ActualizarRestaurante" method="post">
        <div asp-validation-summary="All"></div>
        <div>
            <div class="cons">
                <div>
                    <input asp-for="@Model.Id" type="hidden">
                </div>
                <div>
                    <label asp-for="Nombre">Nombre:</label>
                    <input asp-for="Nombre">
                </div>
                <div>
                    <label asp-for="Precio">Precio:</label>
                    <input asp-for="Precio">
                </div>
            </div>
            <button type="submit">Actualizar</button>
        </div>
    </form>

</body>

</html>

RestoMVC.Mvc/Views/Plato/ActualizarRestaurante.cshtml
@model RestoMVC.Core.Restaurante
@{
    Layout = null;
}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <title>Actualizar - Plato</title>
</head>

<body>
    <form asp-action="ActualizarRestaurante" method="post">
        <div asp-validation-summary="All"></div>
        <div>
            <div class="cons">
                <div>
                    <input asp-for="@Model.Id" type="hidden">
                </div>
                <div>
                    <label asp-for="Nombre">Nombre:</label>
                    <input asp-for="Nombre">
                </div>
                <div>
                    <label asp-for="Direccion">Direccion:</label>
                    <input asp-for="Direccion">
                </div>
                <div>
                    <label asp-for="Mail">Mail:</label>
                    <input asp-for="Mail">
                </div>
                <div>
                    <label asp-for="Telefono">Telefono:</label>
                    <input asp-for="Telefono">
                </div>
                <div>
                    <label asp-for="Contrasenia">Contrasenia:</label>
                    <input asp-for="Contrasenia" type="password">
                </div>
                <div>

                </div>
            </div>
            <button type="submit">Actualizar</button>
        </div>
    </form>

</body>

</html>

RestoMVC.Mvc/Views/Plato/AltaPlato.cshtml
@model RestoMVC.Core.Plato;
@{
    Layout = null;
}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <title>RestoMVC - Platos</title>
</head>

<body>
    <form asp-action="AltaPlato" method="post">
        <div asp-validation-summary="All"></div>
        <div>
            <div class="cons">
                <div>
                    <label asp-for="Nombre">Nombre:</label>
                    <input asp-for="Nombre">
                </div>
                <div>
                    <label asp-for="Precio">Precio:</label>
                    <input asp-for="Precio">
                </div>
            </div><br>
            <button type="submit">Alta Plato</button>
        </div>
    </form>
</body>

</html>

RestoMVC.Mvc/Views/Plato/Detalle.cshtml
@model RestoMVC.Core.Plato
@{
    Layout = null;
}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <title>RestoMVC - Detalle @Model.Nombre</title>
</head>

<body>
    <div class="cons">
        <ul>
            <h3>Restaurante:&nbsp;@Model.Nombre</h3><br>
            <h4> Direccion: @Model.Precio</h4>
        </ul>
        <a asp-action="Index">
            <h2>Platos</h2>
        </a>
    </div>

</body>

</html>

RestoMVC.Mvc/Views/Plato/Listado.cshtml
@using RestoMVC.Core;
@model IEnumerable<Plato>
@{
    ViewData["Title"] = "Platos";
}

<body>
    <table>
        <tbody>
            @foreach (Plato plato in Model)
            {
                <tr>
                    <div>
                        <td>
                            <a asp-controller="Plato" asp-action="Detalle" asp-route-id="@plato.Id"><button
                                type="submit"><b>@plato.Nombre</b></button></a>
                        </td>
                    </div>
                    <div>
                        <td>
                            <a asp-controller="Plato" asp-action="Actualizarplato" asp-route-id="@plato.Id"><button
                                type="submit"><b>Actualizar</b></button></a>
                        </td>
                    </div>
                    <div>
                        <td>
                            <form asp-controller="Plato" asp-action="Eliminarplato" method="post">
                                <input type="hidden" asp-for="@plato.Id">
                                <button type="submit"><b>Eliminar</b></button>
                            </form>
                        </td>
                    </div>
                    <div>
                </tr>
            }
        </tbody>
    </table>
</body>

RestoMVC.Mvc/Views/Restaurante/ActualizarRestaurante.cshtml
@model RestoMVC.Core.Restaurante
@{
    Layout = null;
}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <title>Actualizar - Resto</title>
</head>

<body>
    <form asp-action="ActualizarRestaurante" method="post">
        <div asp-validation-summary="All"></div>
        <div>
            <div class="cons">
                <div>
                    <input asp-for="@Model.Id" type="hidden">
                </div>
                <div>
                    <label asp-for="Nombre">Nombre:</label>
                    <input asp-for="Nombre">
                </div>
                <div>
                    <label asp-for="Direccion">Direccion:</label>
                    <input asp-for="Direccion">
                </div>
                <div>
                    <label asp-for="Mail">Mail:</label>
                    <input asp-for="Mail">
                </div>
                <div>
                    <label asp-for="Telefono">Telefono:</label>
                    <input asp-for="Telefono">
                </div>
                <div>
                    <label asp-for="Contrasenia">Contrasenia:</label>
                    <input asp-for="Contrasenia" type="password">
                </div>
                <div>

                </div>
            </div>
            <button type="submit">Actualizar</button>
        </div>
    </form>

</body>

</html>

RestoMVC.Mvc/Views/Restaurante/FormAlta.cshtml
@model RestoMVC.Core.Restaurante;
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <title>RestoMVC - Restaurantes</title>
</head>
<body>
    <form asp-action="AltaRestaurante" method="post">
    <div asp-validation-summary="All"></div>
    <div>
        <label asp-for="Nombre">Nombre:</label>
        <input asp-for="Nombre">
    </div>
    <div>
        <label asp-for="Direccion">Direccion:</label>
        <input asp-for="Direccion">
    </div>
    <button type="submit">Alta Restaurante</button>
    </form>
</body>
</html>

RestoMVC.Mvc/Views/Restaurante/Login.cshtml
@model RestoMVC.Core.Restaurante;
@{
    Layout = null;
}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <title>Login - Resto</title>
</head>

<body>
    <form asp-action="Login" method="post">
        <div asp-validation-summary="All"></div>
        <div>
            <div class="cons">
                <div>
                    <label asp-for="Mail">Mail:</label>
                    <input asp-for="Mail">
                </div>
                <div>
                    <label asp-for="Contrasenia">Contrasenia:</label>
                    <input asp-for="Contrasenia" type="password">
                </div>
                <div>

                </div>
            </div>
            <button type="submit">IniciarSesion</button>
        </div>
    </form>

</body>

</html>

RestoMVC.Mvc/Views/Restaurante/LoginInicio.cshtml
@model RestoMVC.Core.Restaurante;
@{
    Layout = null;
}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <title>Login - Resto</title>
</head>

<body>
    <form asp-action="Login" method="post">
        <div asp-validation-summary="All"></div>
        <div>
            <div class="cons">
                <div>
                    <label asp-for="Mail">Mail:</label>
                    <input asp-for="Mail">
                </div>
                <div>
                    <label asp-for="Contrasenia">Contrasenia:</label>
                    <input asp-for="Contrasenia" type="password">
                </div>
                <div>

                </div>
            </div>
            <button type="submit">IniciarSesion</button>
        </div>
    </form>

</body>

</html>

RestoMVC.Mvc/Views/Restaurante/Modificar.cshtml
@model RestoMVC.Core.Restaurante
@{
    Layout = null;
}
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <title>Actualizar - Resto</title>
</head>

<body>
    <form asp-action="Modificar" method="post">
        <div asp-validation-summary="All"></div>
        <div>
            <div class="cons">
                <div>
                    <label asp-for="Nombre">Nombre:</label>
                    <input asp-for="Nombre">
                </div>
                <div>
                    <label asp-for="Direccion">Direccion:</label>
                    <input asp-for="Direccion">
                </div>
                <div>
                    <label asp-for="Mail">Mail:</label>
                    <input asp-for="Mail">
                </div>
                <div>
                    <label asp-for="Telefono">Telefono:</label>
                    <input asp-for="Telefono">
                </div>
                <div>
                    <label asp-for="Contrasenia">Contrasenia:</label>
                    <input asp-for="Contrasenia" type="password">
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Actualizar</button>
        </div>
    </form>

</body>

</html>

RestoMVC.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestoMVC.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RestoMVC.Mvc.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RestoMVC.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurante"
                                asp-action="AltaRestaurante">AltaRestaurante</a>
                        </li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Plato"
                            asp-action="AltaPlato">AltaPlato</a>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RestoMVC.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>